# Generated by Django 3.1.3 on 2020-12-03 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('Id_Caso', models.AutoField(primary_key=True, serialize=False)),
                ('Costo', models.PositiveIntegerField()),
                ('Juzgado', models.CharField(max_length=25)),
                ('Materia', models.CharField(max_length=25)),
                ('Estatus', models.CharField(max_length=25)),
                ('CreadoFechaHora', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('Id_Documento', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('path', models.FilePathField()),
                ('CreadoFechaHora', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('Id_Domicilio', models.AutoField(primary_key=True, serialize=False)),
                ('Ciudad', models.CharField(max_length=50)),
                ('Estado', models.CharField(max_length=50)),
                ('Pais', models.CharField(max_length=50)),
                ('Calle', models.CharField(max_length=50)),
                ('Colonia', models.CharField(max_length=50)),
                ('Numero', models.PositiveIntegerField()),
                ('CreadoFechaHora', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('Id_Rol', models.AutoField(primary_key=True, serialize=False)),
                ('Rol', models.CharField(max_length=25)),
                ('CreadoFechaHora', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('Id_Persona', models.AutoField(primary_key=True, serialize=False)),
                ('Curp', models.CharField(max_length=18)),
                ('Telefono', models.CharField(max_length=10)),
                ('Edad', models.CharField(max_length=50)),
                ('Sexo', models.CharField(max_length=2)),
                ('CreadoFechaHora', models.DateTimeField()),
                ('Id_Domicilio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rest_api.domicilio')),
                ('Id_Rol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rest_api.rol')),
                ('Id_User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
